name: gotrue
description: A dart client library for the GoTrue API.
version: 1.5.5
homepage: 'https://supabase.io'
repository: 'https://github.com/supabase/gotrue-dart'

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  http: ^0.13.0
  jwt_decode: ^0.3.1
  universal_io: ^2.0.4
  rxdart: ^0.27.7
  meta: ^1.7.0

dev_dependencies:
  dart_jsonwebtoken: ^2.4.1
  dotenv: ^3.0.0
  lints: ^1.0.1
  test: ^1.16.4
  otp: ^3.1.3

false_secrets:
  - /infra/docker-compose.yml
